### ISSUE TITLE
Insert fastener command doesn't work when diameter is changed #242

### ISSUE THREAD

**Issue by xoviat** [shaise/FreeCAD_FastenersWB#102]
If both the 'fastener' type and 'diameter' is changed, then the insert fastener command fails.

```
09:29:15  At ~\AppData\Roaming\FreeCAD\Mod\fasteners\FSChangeParams.py Line 342
09:29:15  {'sclassname': 'class Base::ValueError', 'sErrMsg': "'#6' is not part of the enumeration", 'sfile': '', 'iline': 0, 'sfunction': '', 'swhat': "'#6' is not part of the enumeration", 'btranslatable': False, 'breported': True}: Inappropriate argument value (of correct type).
```

This may be a fasteners workbench issue? See Zolko-123/FreeCAD_Assembly4#242.

**Comment by luzpaz** [comment]
@xoviat can you discuss this on the forum. It gets a lot more traffic/eyeballs than the Fastener issue queue. See https://forum.freecadweb.org/viewtopic.php?f=8&t=11429

**Comment by luzpaz** [comment]
@xoviat ping

**Comment by luzpaz** [comment]
@berberic2 do you mind weighing-in ?

**Comment by luzpaz** [comment]
@shaise ping

**Comment by shaise** [comment]
I can't reproduce this issue. Changing both fastener type and diameter seems to work even if I switch between Inch/Metric types. Need more info.

**Comment by berberic2** [comment]
> @berberic2 do you mind weighing-in ?
Sorry, can not reproduce…

**Comment by luzpaz** [comment]
@xoviat can you please add you full [about](https://wiki.freecad.org/About) info?

**Comment by alexneufeld** [comment]
This should be closed, since no one has been able to reproduce the problem.

**Comment by shaise** [comment]
closing
