### ISSUE TITLE
Having issues installing Add-on due to missing gif in repo

### ISSUE THREAD

**Issue by egasco** [shaise/FreeCAD_FastenersWB#107]
AddonManager: Debug: Error retrieving image from https://github.com/shaise/FreeCAD_FastenersWB/raw/master/Icons/FastenersScreencast.gif

Using FreeCad: ./FreeCAD_weekly-builds-26155-Linux-Conda_glibc2.12-x86_64.AppImage

**Comment by shaise** [comment]
Thanks for the catch, should be ok now. Please test again.

**Comment by egasco** [comment]
I was able to install! Thanks!
