### ISSUE TITLE
Custom ScrewDie with sm3DPrintMode error

### ISSUE THREAD

**Issue by balogh-attila** [shaise/FreeCAD_FastenersWB#115]
I have got an error "local variable 'dia' referenced before assignment" on the line below, when I try to make a ScrewDie with 3D compatibility mode, and custom thread:
https://github.com/shaise/FreeCAD_FastenersWB/blob/6b86b4bb74cdaf3929bc755d07b7d2c70485814f/screw_maker.py#L3834

I think the code correctly:
```python
         dia = self.smScrewThrScaleA * customDia + self.smScrewThrScaleB
```

**Comment by shaise** [comment]
you are right! and same for line 3873. Fixed now, Thanks!
