### ISSUE TITLE
thread “jump”

### ISSUE THREAD

**Issue by berberic2** [shaise/FreeCAD_FastenersWB#119]
If the thread is generated on a ScrewTap the tab jumps one pitch.
see: https://forum.freecadweb.org/viewtopic.php?f=13&t=64897
there is an example in the third posting

**Comment by shaise** [comment]
Actually the threaded version was in the correct position, but the non threaded "jumped" up.
Should be fixed now. please test.

**Comment by berberic2** [comment]
Works. Thanks

**Comment by luzpaz** [comment]
thanks shaise! Closing
