### ISSUE TITLE
New item

### ISSUE THREAD

**Issue by johnny-bui** [shaise/FreeCAD_FastenersWB#120]
How can I create a new kind of fastener? I want to create a button to make wood pins. They are used in wood working to join wood plate.

**Comment by luzpaz** [comment]
@shaise do we have documentation for this somewhere?

**Comment by shaise** [comment]
I seem to recall that one of the WB contributors wrote something, but I can not seem to find it.
Also, everything is based on the original screw_maker by ulrich1a and it is not trivial to extend.

**Comment by luzpaz** [comment]
@johnny-bui see https://github.com/shaise/FreeCAD_FastenersWB/blob/master/CONTRIBUTING.md

@shaise can be closed

**Comment by shaise** [comment]
closing.
