### ISSUE TITLE
Fasterners duplicate on STEP files when placing them on a face

### ISSUE THREAD

**Issue by ToniTen** [shaise/FreeCAD_FastenersWB#131]
Crossposted from [the forum](https://forum.freecadweb.org/viewtopic.php?p=582079#p582079)

On imported STEPs, cylinders are split into two half-cylinders, and that seems to confuse this function and it ends up with duplicate fasteners. Take this example for a duct flange, that should normally be secured with 30 bolts. If you select the face and try to automatically place the bolts, you end up with not only double the amount of bolts, but also 4 extra screws place in the center.
[Fasteners and Steps.FCStd.zip](https://github.com/shaise/FreeCAD_FastenersWB/files/8323857/Fasteners.and.Steps.FCStd.zip)
[Duct_Flange.STEP.zip](https://github.com/shaise/FreeCAD_FastenersWB/files/8323858/Duct_Flange.STEP.zip)

**Comment by luzpaz** [comment]
@shaise Is this fixed by #132 ?

**Comment by shaise** [comment]
I believe it should but have not tested

**Comment by luzpaz** [comment]
@ToniTen ping  
Do you mind testing?

**Comment by ToniTen** [comment]
> Do you mind testing?

Sorry for the late reply, but yeah, it's fixed
