### ISSUE TITLE
Adding countersunk washer

### ISSUE THREAD

**Issue by hpbmo** [shaise/FreeCAD_FastenersWB#134]
I created the needed files for countersunk washer according NFE27-619. 

https://www.bossard.com/eshop/ch-de/scheiben/scheiben-fuer-senkschrauben/scheiben-gedreht-fuer-senkschrauben-90/p/80077/?category=01.100.300.50&index=6&q=%3Arelevance

My github knowledge is nearly zero. It would be nice, if my creation could be checked and if the changes are ok, they could be integrated. Can I upload the zipped files? Or is creating directly a pull request the correct way?

**Comment by luzpaz** [comment]
Merged in 4fdbc16  
Thanks @hpbmo for your contribution
