### ISSUE TITLE
Where do you guys get your information to create the models for each fastener?

### ISSUE THREAD

**Issue by K4LCIFER** [shaise/FreeCAD_FastenersWB#136]
I find that whenever I want to find general information on dimmensions of say even just a regular metric screw I end up encountering a paywal of a few hundred dollars to acquire the standard from ISO. I was wondering if you guys have a source to acquire standards for free, or if you are paying for each standard when you add more to this workbence.

**Comment by luzpaz** [comment]
Please x-post the question to the official discussion thread https://forum.freecadweb.org/viewtopic.php?f=8&t=11429

**Comment by alexneufeld** [comment]
[http://www.fasteners.eu/](http://www.fasteners.eu/) and [https://en.torqbolt.com](https://en.torqbolt.com) have pages for most of the DIN and ISO fastener standards. Their data tables are ripped straight from the standard pdfs (torrents of which are also available if you look hard enough). Beyond those sources, vendors such as McMaster-Carr and Misumi have detailed enough info/models for most projects.
