### ISSUE TITLE
Possible problem with retranslateUi in screw_maker.py

### ISSUE THREAD

**Issue by Roy-043** [shaise/FreeCAD_FastenersWB#142]
There are duplicate numbers in the list. I do not know what impact this has.

https://github.com/shaise/FreeCAD_FastenersWB/blob/a82636d951c7badd221b35bf922ba73db046eda1/screw_maker.py#L269-L270

https://github.com/shaise/FreeCAD_FastenersWB/blob/a82636d951c7badd221b35bf922ba73db046eda1/screw_maker.py#L278-L279

**Comment by shaise** [comment]
This is a remanent code from the original screw_maker stand-alone macro  and is not used in the workbench at all, hence not an issue. It will probably be removed when screw_maker.py will be refactored.

**Comment by shaise** [comment]
Sounds reasonable.

**Comment by luzpaz** [comment]
Closing in favor of #158
