### ISSUE TITLE
ScrewDie and ScrewTap custom diameter issue.

### ISSUE THREAD

**Issue by Thamone** [shaise/FreeCAD_FastenersWB#145]
I have a problem with ScrewDie and ScrewTap tool. If I select diameter from the list, their size will match. But if I set diameter to the same "Custom value" the size of Die and Tap is too much off.

![13:11:43_26_06_22](https://user-images.githubusercontent.com/28747875/175802361-99e1b299-670e-42bb-b562-85f44f61480c.jpg)

![13:12:35_26_06_22](https://user-images.githubusercontent.com/28747875/175802367-b04ee150-9e8f-4a01-b3e8-a6daebfc1697.jpg)

OS: Manjaro Linux (GNOME/gnome)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.24415 (Git)
Build type: Release
Branch: makepkg
Hash: 476ecf091941bead59b14e44afa6064d5a66afa3
Python version: 3.10.4
Qt version: 5.15.3
Coin version: 4.0.1
OCC version: 7.5.3
Locale: English/United States (en_US)

**Comment by luzpaz** [comment]
CN you reproduce on the latest FreeCAD stable  v0.20? Also can you repaste About info when you do so we know what version of Fasteners WB you're using

**Comment by Thamone** [comment]
Thank you, I'm building Freecad0.20 From AUR and will report you back. For the workbench version, I think it's the latest one because I've tried check addons for update but all are up to date.

**Comment by shaise** [comment]
I can confirm similar results on v20.

**Comment by Thamone** [comment]
I'm now on 

[code]
OS: Manjaro Linux (GNOME/gnome)
Word size of FreeCAD: 64-bit
Version: 0.21.29321 (Git) AppImage
Build type: Release
Branch: master
Hash: 8ee773362e08d703bce9cfdcefd8e4ad424a7d44
Python 3.10.5, Qt 5.12.9, Coin 4.0.0, Vtk 9.1.0, OCC 7.5.3
Locale: English/United States (en_US)
Installed mods: 
  * fasteners 0.3.46
[/code]

I still get the same result but I now change **Thread generation** to **standard mode** and it seem to help.
![12:58:48_27_06_22](https://user-images.githubusercontent.com/28747875/175869748-86064508-63a6-4f00-b899-6802609658ff.jpg)
![12:56:56_27_06_22](https://user-images.githubusercontent.com/28747875/175869766-fbaff17f-7482-438d-8649-a0b74b535d97.jpg)

I'm now set Tap offset = 0.15, Die offset = -0.15, will see if it can fit together.

**Comment by Thamone** [comment]
It is printed out perfect fit with offset 0.15, -0.15 :) 
Thank you
![1656329710708](https://user-images.githubusercontent.com/28747875/175932631-096ea507-1faa-41df-a5e2-61c1ae0defd0.jpg)
.

**Comment by Thamone** [comment]
Oh sorry my bad :P I thought this value was tolerances between the internal and external thread.
