### ISSUE TITLE
Wrong color for DIN 571 Hexagon head wood screw icon?

### ISSUE THREAD

**Issue by Roy-043** [shaise/FreeCAD_FastenersWB#149]
For some reason bright green was selected as the color for the DIN 571 Hexagon head wood screw icon. Considering that the inch fasteners are pale green this is a bit confusing IMO.

**Comment by shaise** [comment]
I think the reason is because the thread is neither metric nor imperial. but I tend to agree that if the sizes are in mm, it should be orange as all other metric fasteners

**Comment by luzpaz** [comment]
Can this ticket be closed, @Roy-043 ?

**Comment by Roy-043** [comment]
Yes.
