### ISSUE TITLE
Add a Screencast to README 

### ISSUE THREAD

**Issue by luzpaz** [shaise/FreeCAD_FastenersWB#15]
This helps users to faster recognize what this Workbench does. Eventually this screencast can be useful when Addon Installer becomes more sophisticated (https://github.com/FreeCAD/FreeCAD-addons/issues/37)

**Comment by luzpaz** [comment]
Adding this can get rid of those 3 pngs and maximize space in the README

**Comment by shaise** [comment]
Done.

**Comment by luzpaz** [comment]
https://github.com/shaise/FreeCAD_FastenersWB/commit/6815235b29bea0a654655fe07d5f886d5053a55b
