### ISSUE TITLE
Refactor `screw_maker.py`

### ISSUE THREAD

**Issue by luzpaz** [shaise/FreeCAD_FastenersWB#158]
Fasteners workbench evolved out of a macro called  `screw_maker.py` created by ulrich of the FreeCAD community. There are still remnants of that macro within the code. This issue is a placeholder for the need to refactor the code and clean it up.

**Comment by shaise** [comment]
Stage 1 complete. screw_maker cleaned and split to separate screw creation files

**Comment by luzpaz** [comment]
@shaise can we close this ticket now? (Thank you for all your efforts recently!)

**Comment by shaise** [comment]
Closing.
