### ISSUE TITLE
thread to short on screws?

### ISSUE THREAD

**Issue by berberic2** [shaise/FreeCAD_FastenersWB#159]
It seems, that the threads on screws are too short. 
I recognized it for ISO 14583, but might hold probably for all.
Maybe a side-effect of the fix from https://github.com/shaise/FreeCAD_FastenersWB/issues/119 ?

![Screenshot_20220804_173904](https://user-images.githubusercontent.com/13178920/182889273-224aecfe-ecca-4ccd-b8d3-b81aa228e91d.png)

**Comment by shaise** [comment]
This is most probably not a side effect of #119, as #119 touched only the threaded rod.
However there is definitely an issue with the thread creation. Aside from not starting from the top, adding threads seems to alter the length of the fastener. And this affects many other fasteners, if not all. I need to dig into it to see how to globally fix this issue.
Thanks for the catch.
shai

**Comment by shaise** [comment]
I had to completely change the interface to the thread creation as it was too complicated to understand and use.
This should solve this issue as well.

**Comment by luzpaz** [comment]
Thanks for refactoring and simplifying the code semantically!

**Comment by shaise** [comment]
@berberic2, can you verify the issue is fixed?

**Comment by berberic2** [comment]
Yep.
As far as I can see, it works fine now.
Thanks.

**Comment by berberic2** [comment]
closing issue…
