### ISSUE TITLE
DIN 1587 broken 

### ISSUE THREAD

**Issue by berberic2** [shaise/FreeCAD_FastenersWB#163]
Hello,

DIN 1587 “Sechskant-Hutmuttern, hohe Form” is broken.

![Screenshot_20220822_153816](https://user-images.githubusercontent.com/13178920/185935265-979ea347-903b-44f2-ba37-b48befe20b49.png)
Nuts are transparent in the image. Size is M6.
Without thread, the hole has no depth.
With thread the thread is to short. For M6 it should be 8 mm, but is only about 6.5 mm.
(As far as I understand, 8 mm is the length of the threaded part of the hole)

**Comment by shaise** [comment]
Thanks. Will check!

**Comment by berberic2** [comment]
![Screenshot_20220822_204032](https://user-images.githubusercontent.com/13178920/185995259-c79119da-4b78-4059-a4f2-2705f3b5ce83.png)

**Comment by luzpaz** [comment]
Thanks!
