### ISSUE TITLE
Automatic label of objects is missing trailing zeros in some cases.

### ISSUE THREAD

**Issue by berberic2** [shaise/FreeCAD_FastenersWB#165]
The automatic label is wrong if the diameter ends with 0.
Par example, instead of “M10-Nut” it gets “M1-Nut”, analog for M20, etc… 

Problem is in FastenersCmd.py · FSScrewObject.CleanDecimals()
which removes trailing zeros even if there is no decimal point.

**Comment by shaise** [comment]
should be fixed now
Thanks!
