### ISSUE TITLE
“move fastener to new location” does not honor placement

### ISSUE THREAD

**Issue by berberic2** [shaise/FreeCAD_FastenersWB#169]
The “move fastener to new location” function does not honor the placement of an object. It moves the Fasteners to the position the selected edge (circle) would have is placement is zero. Initial positioning a fastener (while creating) does honor the placement.

If I try to  “move fastener to new location”  in the attached examples it does not honor the placement of body.

[fasterners_placement.FCStd.gz](https://github.com/shaise/FreeCAD_FastenersWB/files/9462785/fasterners_placement.FCStd.gz)

**Comment by shaise** [comment]
Thanks for the report. I'm on it.

**Comment by shaise** [comment]
Should be fixed now

**Comment by berberic2** [comment]
Now the fasteners follows the object, if placement of object is changes – which is fine,

But now “move fastener to new location” does not work at all. The function does not get activated if a fasteners and a circle-edge is selected.

**Comment by berberic2** [comment]
Thanks.
