### ISSUE TITLE
“Match screw by outer thread diameter (Pass hole)” icon vanishes on switching workbenches.

### ISSUE THREAD

**Issue by berberic2** [shaise/FreeCAD_FastenersWB#170]
If I open the fasterners-workbench for the first time, there are two icons, to select, if outer or inner diameter should be matched. After switching to PartDesign (or probably any other workbench) and back to fasterners the “Match screw by outer thread diameter (Pass hole)” icon is gone.
I mostly need the outer thread diameter option.

![Screenshot_20220831_172729](https://user-images.githubusercontent.com/13178920/187722026-23f1dccb-2d15-41fc-8700-42ef797438be.png)

**Comment by shaise** [comment]
Yes, I encountered this as well. will investigate...

**Comment by shaise** [comment]
It seems to be an internal freecad bug with grouped commands. I have resided to a manual handling of the buttons. Should be OK now.

**Comment by luzpaz** [comment]
@shaise is there an upstream ticket ?

**Comment by shaise** [comment]
I cant say that for sure. I just did not find any reason why a button will disappear when switching workbenches

**Comment by luzpaz** [comment]
Is this still relevant ?

**Comment by shaise** [comment]
as the workaround works, I think we can close this
