### ISSUE TITLE
Completion of the translation.

### ISSUE THREAD

**Issue by FreeCAD-Tools** [shaise/FreeCAD_FastenersWB#182]
The translation is done very well, but there is still a little bit left.

![изображение](https://user-images.githubusercontent.com/90561109/192248547-65eb42cd-2b45-4320-8273-cfab18c12dd2.png)
fasteners types

![изображение](https://user-images.githubusercontent.com/90561109/192246290-1601022a-96df-47b6-a9fd-62763f1e0e07.png)
header, Table headers, default value.

**Comment by FreeCAD-Tools** [comment]
Good work.

I looked at the code and some words are not easy to translate. Since they are related to the code. Like **Default**

**Comment by luzpaz** [comment]
Still relevant ?

**Comment by FreeCAD-Tools** [comment]
The main problem has been solved.
