### ISSUE TITLE
Threaded solids of revolution as first-class citizens

### ISSUE THREAD

**Issue by KOLANICH** [shaise/FreeCAD_FastenersWB#20]
Threads are very widespread in technic, and there are even special conventions to mark threads on blueprints without drawing them.

So I guess that all bodies of revolution in freecad should have a property, making them as threaded. This may allow marking threads when making drawings, marking and showing threads without real rendering them in 3d (for example it is possible to apply a texture or a shader to show them) and importing threads from OpenSCAD (there is a library making threads, but nothing prevents us threat the symbols defined there as intrinsics) keeping them as metadata not a 3d model.

**Comment by shaise** [comment]
Hi Kolanich,
Yes, I guess you are right, but I think right now there is no system in freecad core to treat objects as special entities.

**Comment by luzpaz** [comment]
@KOLANICH I recommend opening a feature request on the FreeCAD forums to discuss this further with the devs and community...

**Comment by luzpaz** [comment]
@KOLANICH care to follow up and create a forum thread to discuss this?

**Comment by alexneufeld** [comment]
This should be closed. It's not relevant to us, as the requested feature would seemingly be part of the FreeCAD core distribution and not an addon module. Therefore there is no work related to the stated problem to be done in this repository.

**Comment by shaise** [comment]
agree. closing
