### ISSUE TITLE
Shape is not a shell when changing cylinder head screw parameters

### ISSUE THREAD

**Issue by james-mcjohnson** [shaise/FreeCAD_FastenersWB#217]
The latest commit (e19ca7317bd6f607300dc5631d663b4d062a9b18) has the following 2 lines:

`743: res[0].Placement = FreeCAD.Placement(FreeCAD.Vector(0,0,0),FreeCAD.Rotation(0,0,0,1))
744: res[1].Placement = FreeCAD.Placement(FreeCAD.Vector(0,0,0),FreeCAD.Rotation(0,0,0,1))`

These cause a "Shape is not a shell" error when changing parameters of a cylinder head screw. By adding a reference to h_a, the error is eliminated:

`743: res[0].Placement = FreeCAD.Placement(FreeCAD.Vector(0,0,h_a),FreeCAD.Rotation(0,0,0,1))
744: res[1].Placement = FreeCAD.Placement(FreeCAD.Vector(0,0,h_a),FreeCAD.Rotation(0,0,0,1))`

**Comment by shaise** [comment]
You are absolutely correct. Thanks!!

**Comment by luzpaz** [comment]
@shaise JFYI, if you use `Fixes #217` then 217 will automagically be closed when commit is merged

**Comment by shaise** [comment]
@luzpaz 
I prefer to let the person who opened it to check and close.

**Comment by luzpaz** [comment]
Just sayin, they can always re-open if issue persists and ticket doesn't get neglected.

**Comment by shaise** [comment]
Thanks. Its a good tip.

**Comment by luzpaz** [comment]
Closing ticket.
