### ISSUE TITLE
UNF/UNC threaded rod

### ISSUE THREAD

**Issue by reox** [shaise/FreeCAD_FastenersWB#22]
Today I was in the need of unified thread standard rods. I patched screwmaker to generate me the 5/16-24 thread:
https://github.com/shaise/FreeCAD_FastenersWB/compare/master...reox:master

I do not know much about inch threads but it seems they are quite the same as the metric ones (except withworth of course...)
So maybe it is worth to integrate more inch threads - but I think it will get quite messy because of all the patching of methods that rely on the metric character...
(if you want to take this seriously, I think you would need to add a lot imperial screws and nuts as well...)

So maybe someone want to take a look at this - or hint me to a workbench that has threaded rods in all variants (I would like to have trapezoidal as well...)

**Comment by hhassey** [comment]
I support @reox  I think we should have threaded rods.

**Comment by hhassey** [comment]
@reox  It looks like you can get the result with the Screw Tap!

**Comment by reox** [comment]
@hhassey what do you mean by Screw Tap? Unfortunately I have no clue what you mean :/

**Comment by luzpaz** [comment]
@hhassey ping

**Comment by rebeltaz** [comment]
I, too, would like to see SAE threads available in the threaded rod tool.

**Comment by oldninja** [comment]
Any plans to support US standards, UNC/UNF threads? @shaise

**Comment by alexneufeld** [comment]
This should be closed. We support inch threaded rod.

**Comment by shaise** [comment]
correct. closed as complete
