### ISSUE TITLE
[Feature Request] Add AddBSplineCurve() function to FSFaceMaker class (FastenerBase.py)

### ISSUE THREAD

**Issue by EA32** [shaise/FreeCAD_FastenersWB#227]
Screw head created by 2 arcs. 5 points
![image](https://user-images.githubusercontent.com/116030160/198334817-d440f674-05ba-43cd-8a29-c44099eef3ec.png)

Screw head created by 1 BSplineCurve. 3 points.
![image](https://user-images.githubusercontent.com/116030160/198333365-1e261641-558c-4905-b3f0-9114b2b2cdeb.png)

Curves allow to avoid a contour when constructing a hemisphere.
And allow to build a contour with fewer points.

**Comment by shaise** [comment]
what is the python command for bspline?

**Comment by FreeCAD-Tools** [comment]
This is code from console:

            App.getDocument('Unnamed').getObject('Sketch').addGeometry(Part.BSplineCurve([App.Vector(-0.44,28.52),App.Vector(40.73,29.41),App.Vector(39.85,-0.58)],None,None,False,3,None,False),False)

I think that should be enough. The name of new function can be shorter Add spline() for example.

**Comment by shaise** [comment]
Thanks!
Feature is added.
To add a spline, simply use:
`addSpline(x1, z1, x2, z2, ..... xn, zn)`
This will add a spline starting at the last point, and going through all points.
Minimum 2 points (2 'x,z' pairs).

**Comment by EA32** [comment]
Thanks! This feature will be useful to me in the near future.

**Comment by FreeCAD-Tools** [comment]
Nobody minds if the function is called AddBSpline instead of simple AddSpline ?

**Comment by EA32** [comment]
Feature coplited. Issue closed.
