### ISSUE TITLE
feature request - square nut

### ISSUE THREAD

**Issue by yo-k** [shaise/FreeCAD_FastenersWB#23]
First at all - thank you for the great fasteners work bench!

Would it be possible to integrate square nuts, too?

https://www.schrauben-lexikon.de/norm/DIN_557.asp
https://www.schrauben-lexikon.de/norm/DIN_562.asp (low version)

Or may be you could give me a hint which code snipped I have to manipulate? I'll try.

Have a nice day!
yo-k

**Comment by shaise** [comment]
I'll see what I can do about it.

**Comment by shaise** [comment]
Done.

**Comment by yo-k** [comment]
Wow, very fast and well done.

Thank you!!!

**Comment by shaise** [comment]
Happy to have helped!
