### ISSUE TITLE
[Optimization] Notes about Settings menu

### ISSUE THREAD

**Issue by FreeCAD-Tools** [shaise/FreeCAD_FastenersWB#238]
Minor notes. Perhaps this is not very important.

1. I found some values in the translation files that are not visible on the screen but taking up space in the *.ts files.
In list it marked as '?'
![изображение](https://user-images.githubusercontent.com/90561109/198984301-da23c045-35a2-451f-b5b7-5a1eae0d3c95.png)

to that values do not includes to the *.tr file, I think they need to be marked with a special attribute notr="true"

                  <property name="prefEntry" stdset="0">
                   <string notr="true">NutThrScaleA</string>
                  </property>
                  <property name="prefPath" stdset="0">
                   <string notr="true">Mod/Fasteners</string>
                  </property>

2. Value B is looks like offset, not a scale...

If the menu will have such labels is it normal?
![изображение](https://user-images.githubusercontent.com/90561109/198986366-aa57d0a6-90ef-4d7f-bee2-f173b128293b.png)

**Comment by shaise** [comment]
regarding 2, agreed and changed. But now it should be fixed in the translations

**Comment by FreeCAD-Tools** [comment]
This not easy work. What about other strings?
Now menu looks as:

![изображение](https://user-images.githubusercontent.com/90561109/199006985-4d2f18da-f349-4074-babc-2d9367e3c1e1.png)

And this is how it could look like:
![изображение](https://user-images.githubusercontent.com/90561109/198986366-aa57d0a6-90ef-4d7f-bee2-f173b128293b.png)

**Comment by FreeCAD-Tools** [comment]
IMO 'Thread generation' string may removed, and 'Scale settings for 3d printing' group box may be a checkable.
If the function is disabled, then the parameters are grayed out, which is clear.
This is at the discretion of the developer, and I don't know code and how to do that.

![изображение](https://user-images.githubusercontent.com/90561109/199191865-f3f01f11-df58-484e-bf98-602fd2ca20e1.png)

About translations.
if we change scale and offset we change totality shape of thread i.e. not only scale. Screw scaling and thread scale settings not fully correct. And formula must be more informative.

**Comment by FreeCAD-Tools** [comment]
Thanks. I think the issue can be closed.
