### ISSUE TITLE
Notes to fasteners menu item names

### ISSUE THREAD

**Issue by FreeCAD-Tools** [shaise/FreeCAD_FastenersWB#244]
https://github.com/shaise/FreeCAD_FastenersWB/blob/9d72f974b53b487a0c59258e8ff545082f02efe1/FastenersCmd.py#L102

The absence of a space between ISO and 4762, is it a typo or is it necessary for something?

https://github.com/shaise/FreeCAD_FastenersWB/blob/9d72f974b53b487a0c59258e8ff545082f02efe1/FastenersCmd.py#L203-L205

For some reason, the name and number of the standard are missing in the lines. Does that need fixing?

**Comment by FreeCAD-Tools** [comment]
And who known for what is space removing added in group names?

https://github.com/shaise/FreeCAD_FastenersWB/blob/9d72f974b53b487a0c59258e8ff545082f02efe1/FastenerBase.py#L127-L134

is possibe to disable that replacing? That's looks strange:

![изображение](https://user-images.githubusercontent.com/90561109/200137154-116beffc-174c-4585-8ab7-15d77512cc16.png)

If fix that panel name would be look as:

![изображение](https://user-images.githubusercontent.com/90561109/200137090-ea237066-dd02-4d30-8df8-f37cf46ca903.png)

Corrected code:

                Gui.addCommand(subcommand, #.replace(" ", ""),
                    FSGroupCommand(cmdsubs[subcommand], subcommand, subcommand))
            else:
                cmdlist.append((subcommand, #.replace(" ", ""),
                               cmdsubs[subcommand], subcommand))

**Comment by shaise** [comment]
I see the tool tip differently: 
![image](https://user-images.githubusercontent.com/5813568/201112749-032e857a-4cad-4425-9d75-99f3e11def10.png)

**Comment by FreeCAD-Tools** [comment]
![изображение](https://user-images.githubusercontent.com/90561109/201378285-336265be-ccc1-4cf9-8416-0e61bbfef029.png)
Place the cursor over the beginning of the panel (Where the strip of dots is), after a while the tooltip should pop up. It will contain the name of the component group.

**Comment by shaise** [comment]
Yes you are right.
I will check if there was a reason for that.

By the way, I usually use the drop down buttons option, it is much less cluttered.
![image](https://user-images.githubusercontent.com/5813568/201478688-7beaffdc-69fe-4149-ae91-3162c63f286f.png)
![image](https://user-images.githubusercontent.com/5813568/201478807-662aff62-28ea-4165-83a5-6e8bbe5fb1fc.png)

and also the group name looks ok:
![image](https://user-images.githubusercontent.com/5813568/201478882-94daa59f-3ad4-4e0e-a44a-cd838e3ad6af.png)

**Comment by FreeCAD-Tools** [comment]
For everything to work properly, need to add one more replace at: cmdlist.append(...
It's not clear why this was added.

    def getCommands(self, group):
        cmdlist = []
        cmdsubs = {}
        for cmd in self.commands[group]:
            command, subgroup = cmd
            if subgroup is not None and GroupButtonMode > 0:
                if not (subgroup in cmdsubs):
                    cmdsubs[subgroup] = []
                    if GroupButtonMode == 2:
                        cmdlist.append(subgroup) # .replace(" ", ""))
                        cmdlist.append("Separator")
                cmdsubs[subgroup].append(command)
            else:
                cmdlist.append(command)
        for subcommand in cmdsubs:
            if GroupButtonMode == 2:
                Gui.addCommand(subcommand, #.replace(" ", ""),
                    FSGroupCommand(cmdsubs[subcommand], subcommand, subcommand))
            else:
                cmdlist.append((subcommand, #.replace(" ", ""),
                               cmdsubs[subcommand], subcommand))
        return cmdlist

**Comment by luzpaz** [comment]
Is this ticket still relevant?

**Comment by FreeCAD-Tools** [comment]
Partially yes.

@luzpaz You decided to close all my issues?

**Comment by luzpaz** [comment]
Only coincidentally. Just cycling through the issue queue to check what's still relevant. Sometimes tickets are neglected to be closed

**Comment by FreeCAD-Tools** [comment]
The main problem has been solved. I think that can be closed.
