### ISSUE TITLE
Some ScrewTap sizes produce bad geometry when threaded.

### ISSUE THREAD

**Issue by macdroid53** [shaise/FreeCAD_FastenersWB#246]
I'm using the latest dev version 0.21 30972 and fasteners 0.4.23

![Snip macro screenshot-3a6eb6](https://user-images.githubusercontent.com/6831752/201425483-d955ff69-c3f8-466c-a101-f7bbf2d54665.png)
[FastenersError-mac.FCStd.zip](https://github.com/shaise/FreeCAD_FastenersWB/files/9993049/FastenersError-mac.FCStd.zip)

Am I doing something wrong?

**Comment by alexneufeld** [comment]
nothing wrong on your end. The thread generation code needs cleaning up. Give me some time to put a patch together.

**Comment by TomSaw** [comment]
I'm also affected: diameter >= M24 does not produce solids anymore.
![ThreadedRod broken](https://user-images.githubusercontent.com/738535/206914580-34ab2cec-11d7-4620-a976-cafc490d8a13.png)
