### ISSUE TITLE
[Feature request] Hide custom pitch for non custom thread

### ISSUE THREAD

**Issue by Kuzma30** [shaise/FreeCAD_FastenersWB#255]
In metric theaded rod for tapping holes when you select diametr from the list and want specify Pitch Custom you fail. Custom Pitch values will work only when you select "Custom" for diametr parametr.
May be we can hide "Pitch custom" parametr while diametr not custom?

**Comment by shaise** [comment]
I am not aware of any way to hide a parameter in the properties. however I have just changed the version such that if you touch the pitch custom value, it will automatically change diameter to Custom.
