### ISSUE TITLE
ISO-10642 countersink angle incorrect

### ISSUE THREAD

**Issue by ChrisDumont** [shaise/FreeCAD_FastenersWB#263]
From the Fasteners workbench the default ISO 10642 M6x8 hexagon socket countersunk head screw has the correct 90º countersink angle. But an M2.5x4 screw is about 78º. It should also be 90º shouldn't it?

**Comment by alexneufeld** [comment]
Could you confirm that you are using the latest version of the workbench?
I can't reproduce this issue:
![image](https://user-images.githubusercontent.com/37948669/221430208-28d56579-ef97-4d8f-81f9-9e58e761e174.png)

The countersunk head generation code was updated recently (cac2e85)

**Comment by ChrisDumont** [comment]
I found the problem. I installed Freecad around January 2022 and had forgotten that the Fasteners workbench was installed separately. I've recently installed 0.20.2 but didn't remember to update the workbench. This issue can be closed. Sorry for the noise.

Thanks,
Chris
