### ISSUE TITLE
DIN 975 Threaded Rod dimensions 

### ISSUE THREAD

**Issue by shmishleniy** [shaise/FreeCAD_FastenersWB#265]
Hi,

threaded rod is always bigger than needed because of this:
https://github.com/shaise/FreeCAD_FastenersWB/blob/2fba1ae5cb3dff9634d2045e169afc29f5b6059c/FsFunctions/FSmakeThreadedRod.py#L46

found the initial commit that introduced `4026 Hexagon socket` and `DIN 975 Threaded Rod` with this multiplier `1.01`:
https://github.com/shaise/FreeCAD_FastenersWB/commit/61a108d37011435b0571be5014a259aef1ab69d1

and I don't see that multiplier in the current version for `4026`. Is this multiplier still valid for `DIN 975`?
I can't find a standard but this multiplier is annoying.

**Comment by shaise** [comment]
Hi, Thanks for noticing.
The 1.01 is an old factor remnant that was used in the original thread creation code since diameter integer values caused the thread creation to fail. In the new code it is no longer needed so I removed it.
