### ISSUE TITLE
Purpose of parenthesis in diameter dropdown

### ISSUE THREAD

**Issue by frankhommers** [shaise/FreeCAD_FastenersWB#28]
What is the purpose of the parenthesis in the diameter dropdown on some fasteners?

E.g. diameter: (M27) is with parenthesis and M24 is not.

**Comment by shaise** [comment]
The fastener generation code is taken from "screw_maker" macro by Ulrich. I think its because the parenthesis ones are less standard but not sure.

**Comment by frankhommers** [comment]
Ah OK. I also found it in this table to have the same notation. 

![image](https://user-images.githubusercontent.com/7355878/44573407-d2ddaf00-a786-11e8-9a39-65f41ab7d512.png)

I guess you are right. Thanks
