### ISSUE TITLE
[Question] configuration files for translation handling

### ISSUE THREAD

**Issue by kaktusus** [shaise/FreeCAD_FastenersWB#281]
There is nothing in the translator's [guide](https://github.com/shaise/FreeCAD_FastenersWB/blob/master/TRANSLATIONS.md) about the `create_ts.py` file.
Should it be updated when new languages are added?

**Comment by shaise** [comment]
@riqueenz can you comment ?

**Comment by riqueenz** [comment]
>There is nothing in the translator's [guide](https://github.com/shaise/FreeCAD_FastenersWB/blob/master/TRANSLATIONS.md) about the create_ts.py file.
>Should it be updated when new languages are added?

No, the create_ts.py and compile_ts.py files are deprecated and it is only necessary to update the update.sh file as it is in the guide.

**Comment by kaktusus** [comment]
Thank you for the clarification.
:wink:
