### ISSUE TITLE
Updating Fastener WB to be compatible with the upcoming 0.18 release (req. py3 and Qt5 compatibility)

### ISSUE THREAD

**Issue by luzpaz** [shaise/FreeCAD_FastenersWB#29]
ref: https://github.com/FreeCAD/FreeCAD-addons/issues/93

**Comment by shaise** [comment]
Done.

**Comment by luzpaz** [comment]
@shaise Great! That was fast!  
I will make a notation on the forum thread. Cheers!

**Comment by shaise** [comment]
Well Conda's build was a great helper.
