### ISSUE TITLE
The die tool has the wrong profile. It creates the screw with the profile of a nut.

### ISSUE THREAD

**Issue by cnuehll** [shaise/FreeCAD_FastenersWB#298]
green is a M6 screw and red is the ScrewDie-tool
The die-tool (red) does not match the screw (green)

I expect that the ScrewDie-tool (red) creates a screw profile matching the screw (green)

![2023-10-14_22:41:05](https://github.com/shaise/FreeCAD_FastenersWB/assets/147948966/16c69755-7f36-44c9-8115-c13b815a49dc)

![2023-10-14_22:45:30](https://github.com/shaise/FreeCAD_FastenersWB/assets/147948966/1a9fba7b-aeee-462b-9898-e4909ef3b3ee)

here it is well explained how the boolean between a cylinder and the ScrewDie-tool creates a screw:
https://github.com/shaise/FreeCAD_FastenersWB/issues/64#issuecomment-632810462

**Comment by shaise** [comment]
You are correct. It looks like someone messed the original code which was correct. I will take a look.

**Comment by shaise** [comment]
It should be fixed now. Please check.

![image](https://github.com/shaise/FreeCAD_FastenersWB/assets/5813568/1be196c6-6ae9-476b-a53d-097425b9efed)

**Comment by cnuehll** [comment]
V0.4.67 works for me. I tested on freecad 0.21.1.33694  and  0.22.0dev.33909 AppImage. Thank you very much for the super fast fix.
