### ISSUE TITLE
Parametric heatset inserts as an option?

### ISSUE THREAD

**Issue by kozross** [shaise/FreeCAD_FastenersWB#300]
A lot of 3D printed designs use these, and being able to put them into an assembly without having to find a model would help both designers and users. A [parametric model exists](https://print.grabcad.com/library/m3-heat-set-screw-inserts-for-3d-printing-1) for this kind of insert (SolidWorks only, unfortunately).

**Comment by e-dreyer** [comment]
This is a great idea. OpenSCAD did well wit their general use libraries. FreeCAD should also support such things!

**Comment by kozross** [comment]
In particular, these allow control of not only the thread (which is already possible in the existing workbench), but also the length and diameter of the insert itself, which can vary considerably. It is this variability that I'd like to be made available.

**Comment by shaise** [comment]
I have added option co change length / external diameter:
![image](https://github.com/shaise/FreeCAD_FastenersWB/assets/5813568/f6b97315-e9e1-4862-9408-07db214fbabb)
![image](https://github.com/shaise/FreeCAD_FastenersWB/assets/5813568/1b2bb6a1-85b2-4a78-bf09-e0559f0cce7d)

please test.

**Comment by shaise** [comment]
@kozross , can this issue be closed?

**Comment by hasecilu** [comment]
I tested it and proves to be useful, previously I found differences in dimensions with the inserts I have and this fixes that.

**Comment by kozross** [comment]
Likewise. Works great!

**Comment by shaise** [comment]
good. closing this issue.
