### ISSUE TITLE
Hide ISO or ASME parts

### ISSUE THREAD

**Issue by wasteoinc** [shaise/FreeCAD_FastenersWB#305]
As the library becomes more rich it also becomes more clogged and difficult to navigate. Is there already or could I help out to make a button that hides/shows all the ISO or ASME parts?

I live in Europe so I practically never use ASME fasteners. If you could guide me where to I could also try to implement it myself

Thanks for a great workbench

**Comment by shaise** [comment]
yes indeed!
activate the workbench, then go to edit -> preferences  and select fasteners on the left.
You can then have an option to select which type of fasteners to show:
![image](https://github.com/shaise/FreeCAD_FastenersWB/assets/5813568/d04b5b58-3ba2-4985-8452-352017aa6dab)

you can also change the grouping to drop-down, so it will take less space on the toolbar.

**Comment by wasteoinc** [comment]
Wow!  A new world opened to me :) Thanks a bunch
