### ISSUE TITLE
[BUG] Segementation fault when moving an object

### ISSUE THREAD

**Issue by anno0** [shaise/FreeCAD_FastenersWB#317]
Hello,

there is a segmentation fault when moving a fastener. I posted it at FreeCAD forum.

https://forum.freecad.org/viewtopic.php?t=83825

**Comment by shaise** [comment]
It has nothing to do with fastener workbench. you can delete all fasteners, create a cube in part workbench, and when you move it you get the same `<Exception> Access violation`

**Comment by hasecilu** [comment]
This should be closed, it was even patched on upstream FreeCAD

**Comment by shaise** [comment]
agree.
