### ISSUE TITLE
List of pins

### ISSUE THREAD

**Issue by hasecilu** [shaise/FreeCAD_FastenersWB#318]
I made a few pins and saw other ISO norms, so I made a list with them.

Non-exhaustive list of implemented types of pins.

Video-reference: https://youtu.be/W-0ZV9zXpc0         

### Split pins
- [X] Split pins - **ISO1234**

### Clevis pins                                           
- [X] Single hole clevis pins, without head - **ISO2340**, 
- [X] Single hole clevis pins, with head - **ISO2341**
- [ ] Adjustable clevis pins                            
- [ ] Quick release detent clevis pins                  
- [ ] Clevis pins with grooves                             

### Dowel/Parallel pins                                            
- [X] Plain dowel pins **ISO2338**
- [X] Dowel pins - **ISO8734**                              
- [X] Parallel Pins with Internal Thread - **ISO8733**
- [X] Parallel Pins with Internal Thread - **ISO8735**
- [ ] Tapped dowel pins                                 
- [ ] Stepped dowel pins                                                          

### Taper pins                                            
- [X] Plain taper pins - **ISO2339**
- [X] Taper pins with Internal Thread - **ISO8736**         
- [X] Taper pins with external thread - **ISO8737**

### Roll/Spiral pins       
- [x] Spring-type straight pins, Coiled pins, heavy duty - **ISO8748**
- [X] Spring-type straight pins, Coiled, standard duty - **ISO8750**
- [X] Spring-type straight pins, Coiled, light duty - **ISO8751**                                             
- [X] Slotted Roll tension pins (C shape) - **ISO8752**
- [X] Slotted spring pins, light duty - **ISO 13337**
- [ ] Toothed slotted spring pins (skew proof)   

### Grooved pins                                          
- [X] Full-length parallel grooved - **ISO8739**
- [X] Full-length parallel grooved - **ISO8740**
- [X] Third length centre grooved pins - **ISO8742**        
- [X] Half length centre grooved pins - **ISO8743**         
- [X] Full length taper grooved pins - **ISO8744**          
- [X] Half length taper grooved pins - **ISO8745**          
- [x] Round Head Grooved Pins - ISO8746                 
- [x] Countersunk Head Grooved Pins - ISO8747           
- [ ] Half reverse taper grooved pins                   
- [ ] Headed grooved pins

**Comment by alexneufeld** [comment]
Note that I have this branch almost ready to merge. [https://github.com/alexneufeld/FreeCAD_FastenersWB/tree/metric_pins_merge](https://github.com/alexneufeld/FreeCAD_FastenersWB/tree/metric_pins_merge)

It has every ISO standard pin that I could find

**Comment by hasecilu** [comment]
Oops, https://github.com/hasecilu/FreeCAD_FastenersWB/tree/pins

Do we have and official thread on the forum for WIP?

**Comment by alexneufeld** [comment]
No forum thread. I just need to fix up the diameter matching functionality and we'll merge it ASAP. shouldn't take long

**Comment by hasecilu** [comment]
I tested you branch, looks very good!
- I would just change in the descriptions the first letter to be uppercase (to be consistent with all other descriptions)
- In the ISO2341 there is **A** (no hole) and **B** (with hole) types, should be both offered?
