### ISSUE TITLE
Fix up the Fasteners FC wiki page

### ISSUE THREAD

**Issue by luzpaz** [shaise/FreeCAD_FastenersWB#33]
@yorikvanhavre is intent on having all workbenches have some representation on the wiki. The Fasteners WB is at www.freecadweb.org/wiki/Sandbox:Fasteners
Lets move it out of Sandbox and soup it up?

Also I wonder if there is a way for mediawiki to mirror the changelog for Fasteners on Github ? That way WB authors don't need to do double work when they modify their WBs (unless they add/remove feature(s) which then merits editing the wiki)

**Comment by shaise** [comment]
As soon as I have time... :)

**Comment by luzpaz** [comment]
I've moved the page out of the sandbox http://www.freecadweb.org/wiki/Fasteners_Workbench

**Comment by luzpaz** [comment]
@shaise JIC (you probably already know anyway), there are some broken image links on that wiki page.

**Comment by shaise** [comment]
Hi,
I did not make this wiki page. How can I help?

**Comment by luzpaz** [comment]
Oh if that's the case, I'm not sure then. Perhaps take a look at it and see if there is anything you think people should be aware about ? If you are feeling comfortable with the idea, you could make a youtube clip or a screencast of the workbench in action? Whatever you think.

I think you should also add the https://www.freecadweb.org/wiki/Fasteners_Workbench links somewhere in the README.md as well.

**Comment by luzpaz** [comment]
I started to do this recently

**Comment by shaise** [comment]
You are definitely my FreeCad Hero!

**Comment by luzpaz** [comment]
![image](https://user-images.githubusercontent.com/4140247/113212928-6e8c0180-9245-11eb-822b-27cb9a70ace9.png)

Created placeholder pages for all but 2 pages mentioned in the Fasteners Workbench wiki page

**Comment by luzpaz** [comment]
correction: placeholder now exist for all pages

**Comment by shaise** [comment]
Thanks!!!!
Added a link to the wiki in readme.md
