### ISSUE TITLE
Invalid character initialization error

### ISSUE THREAD

**Issue by silopolis** [shaise/FreeCAD_FastenersWB#34]
Hi,

When starting Freecad (FreeCAD_0.18.15150_Conda_Py3Qt5_glibc2.12-x86_64.AppImage) I get the following error:

``During initialization the error invalid character in identifier (<string>, line 1) occurred in /home/tarax/.FreeCAD/Mod/fasteners/InitGui.py
``

**Comment by luzpaz** [comment]
I can't recreate this on FreeCAD_0.18.15671_Conda_Py3Qt5_glibc2.12-x86_64.AppImage

**Comment by luzpaz** [comment]
@silopolis can you recreate this on the latest 0.18.2 stable or 0.19_pre ?

**Comment by luzpaz** [comment]
@silopolis ping

**Comment by luzpaz** [comment]
@shaise i think it's ok to close this ticket

**Comment by shaise** [comment]
agreed.
