### ISSUE TITLE
ASME 18.2.1.6 UNC Hex Head Screw no longer visible

### ISSUE THREAD

**Issue by ppemawm** [shaise/FreeCAD_FastenersWB#349]
This fastener is no longer visible in the Fasteners or Assembly4 workbenches.  I randomly checked a few others and did not find any other that were not visible but did not check all of them.  This occurred sometime in the last few up dates but I do not know exactly which.
![Screenshot 2024-03-02 144836](https://github.com/shaise/FreeCAD_FastenersWB/assets/145160383/63ce4411-0cc1-4012-8375-feef2d861ba9)

```
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34959 (Git)
Build type: Release
Branch: main
Hash: 640018bfa7878a79e1b3c220ddd488d66464dc70
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * Assembly4 0.50.7
  * DynamicData 2.60.0
  * fasteners 0.5.12
  * freecad.gears 1.2.0
  * MnesarcoUtils 0.2.5
  * QuickMeasure 2022.10.28
```

**Comment by Yrii77** [comment]
как скачать менеджер дополнений?

**Comment by ppemawm** [comment]
> the fastener should be back now, please check

It is.  BTW I had to uninstall Fasteners with the AddOn workbench and re-install it in order for the changes to take effect.  Update is not enough even with restart.  

In any event, thank you, especially for the quick response.
