### ISSUE TITLE
Feature Request: Appearance

### ISSUE THREAD

**Issue by berberic2** [shaise/FreeCAD_FastenersWB#359]
I like the possibility to change the default color (V0.5.16 05 Apr 2024: Add option to set fasteners default color.)

What I often use is either setting the `Line Width` and `Point Size` to 1 or setting the `Display Mode` to `Shaded` to give it a lower visual profile.

This might be an unusual personal quirk, but setting at least the default `Point Size` to 1 seems to be sensible, because the objects can’t be edited anyway.

![Screenshot_20240408_132245](https://github.com/shaise/FreeCAD_FastenersWB/assets/13178920/824cf4d6-a479-4ec9-8606-c09449ae32d7)

**Comment by shaise** [comment]
Good Idea, I'll add it as well.

**Comment by berberic2** [comment]
Thanks :)
