### ISSUE TITLE
Update icons

### ISSUE THREAD

**Issue by maxwxyz** [shaise/FreeCAD_FastenersWB#360]
I want to adjust some icons, not a complete overhaul to match stroke size and appearance of the modification tools of Fasteners WB (like BOM, move, flip,...).
Currently they are blue, the WB icon is green.
@shaise should I make the modification tool icons green like the WB icon or should they stay blue (or yellow like parts) and the WB icon also changed to blue (or yellow)?
![grafik](https://github.com/shaise/FreeCAD_FastenersWB/assets/6246609/8a6e0de2-2e95-4838-8c02-6de0e7202e0d)

**Comment by shaise** [comment]
Hi @maxwxyz 
I'm really open to any suggestion. right now the tools are blue, the Imperial fasteners are Cyan, and the metrics are orange.
Maybe we should pick 3 new colors from freecad's standard palette?

**Comment by maxwxyz** [comment]
Following the discussion in the DWG I changed the modification icons to blue including the WB icon.
