### ISSUE TITLE
DIN ISO 14581

### ISSUE THREAD

**Issue by Roundwolf** [shaise/FreeCAD_FastenersWB#364]
Hi all and @shaise , 

I managed to implement the DIN ISO 14581 into my FastenersWB. I would like to share the changes, so they can be implemented in the next Update. Where would be the best place to upload my files? Sorry for this question but I am very new to Coding generally. But my code works, except for the translation to other languages than English.

**Comment by shaise** [comment]
Hi. 
Are you familiar with github and git in general?
Basically you need to fork this repository into your github account: 
![image](https://github.com/shaise/FreeCAD_FastenersWB/assets/5813568/21031b33-6978-4af6-9999-cff2f61693f7)
Then clone it into your computer.
Do the changes then push them back to github.
Once you did it you need to create a "pull request", and this will automatically alert me that you have changes you want to merge. I can then do it automatically.

**Comment by Roundwolf** [comment]
To be honest, I'm not familiar with git yet, so thanks for the explanation. I will try it the way you explained it. And I'll let you know if something doesn't work.

**Comment by shaise** [comment]
Great!
Starting with git is not easy, but there are lots of video tutorials at youtube I'm sure.
