### ISSUE TITLE
Not very happy with the shape of “GN 506 T-Slot nuts to swivel in”

### ISSUE THREAD

**Issue by berberic2** [shaise/FreeCAD_FastenersWB#372]
With this shape it would not be possible to swivel the nut in. 

Image
Left: FreeCAD
Right: Item 0037001 Nutenstein 5 St M5
![A](https://github.com/shaise/FreeCAD_FastenersWB/assets/13178920/f44d504d-41ec-4ed9-87a1-61d82063215e)

**Comment by hasecilu** [comment]
Yeah, it need a tweak on the Bezier curve to be less round, the nut is from Ganter: https://www.elesa-ganter.in/en/ind/Machine-elements--T-Nuts--GN506#listtype=search&term=GN%20506

**Comment by hasecilu** [comment]
Modifying the intermediate point(s) of the spline (blue) we can change the geometry.

Moving the point from the corner will help, maybe we need 2 points instead to make it less pointy.

Could you try to tweak the point(s) position(s) to make it similar to your other model?
![image](https://github.com/shaise/FreeCAD_FastenersWB/assets/53124818/6ebd7b91-353f-4419-9bb2-3adf2bfe1aa2)
![Screenshot_2024-05-02_09-04-49](https://github.com/shaise/FreeCAD_FastenersWB/assets/53124818/54521edf-9b24-44b0-8abf-08fef386b718)

**Comment by berberic2** [comment]
Proposal:

![Screenshot_20240509_164513](https://github.com/shaise/FreeCAD_FastenersWB/assets/13178920/f510a00a-0b3d-4cc0-86df-bdeee0156c2c)

PR: https://github.com/shaise/FreeCAD_FastenersWB/pull/378
