### ISSUE TITLE
The future of Todo.md

### ISSUE THREAD

**Issue by luzpaz** [shaise/FreeCAD_FastenersWB#38]
Should the remaining items in [Todo.md](https://github.com/shaise/FreeCAD_FastenersWB/blob/master/TODO.md) be added to Issues and then the file removed ?

**Comment by shaise** [comment]
does it mater?

**Comment by luzpaz** [comment]
lol, in the grand scheme of things,nprolly not. My inclination is to keep things tidy. Obviously it's your perogative which I defer to.

**Comment by shaise** [comment]
well, I guess this file can be removed. It is not updated anyway
