### ISSUE TITLE
Add angle shift / offset for fasteners

### ISSUE THREAD

**Issue by maxwxyz** [shaise/FreeCAD_FastenersWB#394]
From https://forum.freecad.org/viewtopic.php?p=614456#p614456

It would be great to have also an angle offset (like the length offset) to shift the angle from the default placement.
If you want the nut to be linked to the base object but want to edit the rotation in the placement dialog or via the transform tool it always resets after applying the transform. 
There is currently no solution if the part has a groove for the nut and you need to rotate the nut 30° around its thread axis.

![Peek 2022-08-02 09-12](https://github.com/user-attachments/assets/ca02ddfd-a791-4632-85d2-f55c36f47d50)

@shaise FYI, I've created the issue here from the forum thread to not loose track.

**Comment by alexneufeld** [comment]
A more comprehensive solution would be to switch to using Part::AttachExtensionPython 
https://wiki.freecad.org/Scripted_objects_with_attachment
This would also improve support for other common cases of fastener placement, such as slots or square holes

**Comment by shaise** [comment]
I will add this option, but as I understand with the integration of assembly wb, the right way to do it is using the assembly?

**Comment by maxwxyz** [comment]
Not sure if therefore an Update in Assembly WB is necessary? If so, I think this won't be done for 1.0 I guess.

**Comment by shaise** [comment]
I think assembly supports orientation of joints.

**Comment by shaise** [comment]
Option to rotate the fastener added.
![image](https://github.com/user-attachments/assets/41d82aff-e2de-4c2e-a570-1a0330e30622)

**Comment by maxwxyz** [comment]
Thanks, I'll close it then.
