### ISSUE TITLE
Add some way to force clear cache or reset after changing preferences

### ISSUE THREAD

**Issue by sekwah41** [shaise/FreeCAD_FastenersWB#395]
Ive added a quick dirty one on my local version which is

```python
# Command to clear the FSCache
class FSClearCacheCommand:
    """Clear Fastener Cache command"""

    def GetResources(self):
        return {
            'Pixmap': os.path.join(iconPath, 'IconClearCache.svg'),
            'MenuText': translate("FastenerBase", "Clear Cache"),
            'ToolTip': translate("FastenerBase", "Clear the fastener cache to reset all cached fasteners")
        }

    def Activated(self):
        global FSCache
        FSCache = {}
        FreeCAD.Console.PrintLog("Fastener cache cleared.\n")
        return

    def IsActive(self):
        return True

# Adding the command to FreeCAD
FreeCADGui.addCommand("Fasteners_ClearCache", FSClearCacheCommand())
FSCommands.append("Fasteners_ClearCache", "command")
```

Though when changing the settings for scaling to assist with 3d printing you have to re-open the app or alter one of the settings because they keys don't seem to take into account any of the scaling values.

Another option would possibly be to invalidate the cache if the settings are altered?

**Comment by wavexx** [comment]
I've run into a similar issue just now where changing the thread settings in the preferences didn't clear the existing cache.
Looks like there is already some provision to invalidate the cache when preferences are changed, but it's not working as intended.
