### ISSUE TITLE
Fastener name of Spacer and Standoff with double x

### ISSUE THREAD

**Issue by maxe22** [shaise/FreeCAD_FastenersWB#397]
The auto generated name at fasteners Spacers and Standoff have two "x" between the length and width.
![grafik](https://github.com/user-attachments/assets/420cb713-7083-4c90-804b-410ace40a55a)

Is that desired?
In my opinion there should be only one "x", like
![grafik](https://github.com/user-attachments/assets/4c015c83-1365-4c70-aa66-393183378d47)

In FastenersCmd.py the value for "dispWidth = 'x' + fp.Width" should be changed to "dispWidth = fp.Width"
```
      # Formation of fastener name: DxLxH(LH)-Type
        dispDiam = self.CleanDecimals(self.calc_diam)
        label = dispDiam
        if hasattr(fp, 'Length'):
            dispLen = self.ActiveLength(fp)
            label += 'x' + dispLen
            if hasattr(fp, 'Width'):
                dispWidth = fp.Width
                label += 'x' + dispWidth
```

**Comment by shaise** [comment]
You are right! fixed. Thanks for the catch.

**Comment by luzpaz** [comment]
CLose ?

**Comment by shaise** [comment]
I usually wait for the issuer to close.

**Comment by maxe22** [comment]
I have tested it and it can be closed. Thanks!
