### ISSUE TITLE
3d Printing nut scaling effects both screwtap and nut

### ISSUE THREAD

**Issue by mikasaari** [shaise/FreeCAD_FastenersWB#404]
Hi,

  FreeCAD: FreeCAD_weekly-builds-38946
  Fasteners WB: 0.5.29
  ScrewTap: (M14)
  DIN934 Nut: (M14)

  I am trying to print ScrewTap and suitable Nut for it. When I am tweaking the scaling Nut scaling scales both ScrewTap and Nut. Also I have to restart FreeCAD to get the scaling to effect. If I change the scaling values, then apply and then create totally new Nut, the earlier values still effect. After saving and restarting the FreeCAD new values are applied.

  Thanks a lot for tips.

**Comment by shaise** [comment]
Screw tap is - as named - to tap threads into solid holes. You probably want a threaded rod - and then the scaling will work correctly.
And yes, this is a current limitation that you need to restart freecad. hope to fix it soon.

**Comment by mikasaari** [comment]
Ah, OK. The Threaded Rod layout has "rounded" ends and that is not suitable for my purposes so I selected ScrewTap. But since this is wanted behaviour, I will play with the one setting. Indeed the length change effected immediatelly. Thanks a lot for help!

**Comment by shaise** [comment]
you can use boolean operations to 'cut' the ends of a threaded rod
