### ISSUE TITLE
can not start the Fasteners WB

### ISSUE THREAD

**Issue by DJKyomi** [shaise/FreeCAD_FastenersWB#45]
OS: Ubuntu 18.04.2 LTS
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.1.
Build type: Release
Python version: 2.7.15rc1
Qt version: 5.9.5
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: German/Germany (de_DE)

Error:

![image](https://user-images.githubusercontent.com/39458089/55890723-7ca56b00-5bb3-11e9-96cf-2fd997ee1916.png)

invalid literal for int() with base 10: '18.1'
Traceback (most recent call last):
  File "<string>", line 45, in Initialize
  File "/home/rene/.FreeCAD/Mod/fasteners/FastenerBase.py", line 58, in <module>
    DropButtonSupported = int(FreeCAD.Version()[1]) > 15 # and  int(FreeCAD.Version()[2].split()[0]) >= 5165

**Comment by elf128** [comment]
Pull request #47 have been created. Please wait for approval and integration.
