### ISSUE TITLE
Add LGTM badge

### ISSUE THREAD

**Issue by luzpaz** [shaise/FreeCAD_FastenersWB#58]
https://lgtm.com/projects/g/shaise/FreeCAD_FastenersWB/?mode=list

```
[![Total alerts](https://img.shields.io/lgtm/alerts/g/shaise/FreeCAD_FastenersWB.svg?logo=lgtm&logoWidth=18)](https://lgtm.com/projects/g/shaise/FreeCAD_FastenersWB/alerts/)
```

Example: [![Total alerts](https://img.shields.io/lgtm/alerts/g/shaise/FreeCAD_FastenersWB.svg?logo=lgtm&logoWidth=18)](https://lgtm.com/projects/g/shaise/FreeCAD_FastenersWB/alerts/)

**Comment by luzpaz** [comment]
Also
```
[![Language grade: Python](https://img.shields.io/lgtm/grade/python/g/shaise/FreeCAD_FastenersWB.svg?logo=lgtm&logoWidth=18)](https://lgtm.com/projects/g/shaise/FreeCAD_FastenersWB/context:python)
```

Example: [![Language grade: Python](https://img.shields.io/lgtm/grade/python/g/shaise/FreeCAD_FastenersWB.svg?logo=lgtm&logoWidth=18)](https://lgtm.com/projects/g/shaise/FreeCAD_FastenersWB/context:python)

**Comment by shaise** [comment]
where to add it to?

**Comment by luzpaz** [comment]
I'll send a PR :wink:
