### ISSUE TITLE
[enhancement] standoff+spacers option

### ISSUE THREAD

**Issue by easyw** [shaise/FreeCAD_FastenersWB#62]
For electronics assemblies it would be nice to add [standoff & spacers](https://www.we-online.com/catalog/en/SSTIE_STEEL_SPACER_STUD_METRIC_INTERNAL_EXTERNAL/?sq=standoff+spacers&sp=https%3A%2F%2Fwww.we-online.com%2Fweb%2Fen%2Fwuerth_elektronik%2Fsearchpage.php%3Fsearch%3Dstandoff%2Bspacers) like in the linked documentation
![standoff](https://user-images.githubusercontent.com/3032347/79280718-665e7900-7eb1-11ea-8ee2-68365072a40e.jpg)
![standoff](https://user-images.githubusercontent.com/3032347/79322092-a141ca80-7f0c-11ea-800c-a68988b7fe0c.png)

**Comment by shaise** [comment]
Good idea. Hope to have time for it soon. A bit busy now with my [LinuxCNC](https://github.com/shaise/GrblCNC) clone now.

**Comment by easyw** [comment]
@shaise 
thanks for having a look. 
Spacers and Standoff are available as [CadQuery python scripts](https://github.com/easyw/kicad-3d-models-in-freecad/tree/master/cadquery/FCAD_script_generator/Standoff_FF_MF), but having a python feature in FC as for the screws would be the best.

**Comment by shaise** [comment]
Done.

**Comment by easyw** [comment]
@shaise 
that was fast! :smile:
Would it be possible to also add spacers (which are a sub case of standoffs)?
[spacers](https://www.we-online.com/catalog/en/SSTII_STEEL_SPACER_STUD_METRIC_INTERNAL_INTERNAL/)
![spacer](https://user-images.githubusercontent.com/3032347/79383720-f52ccd80-7f65-11ea-8eda-e48fd20dc56d.jpg)

**Comment by shaise** [comment]
Done as well. Only because you are the one who asked....

**Comment by easyw** [comment]
Thanks a lot!!! Great Tool 😸 
I 've found a minor issue (spacer without icon) at this line:
https://github.com/shaise/FreeCAD_FastenersWB/blob/69e5e04e268642e7cc177b746b643469980a5278/PEMInserts.py#L997
should be changed with:
`FastenerBase.FSClassIcons[FSPcbSpacerObject] = 'PCBSpacer.svg'
`
thanks again, this will be very useful for KiCAD integration 😄

**Comment by shaise** [comment]
ooops... fixed.

**Comment by easyw** [comment]
thx again 😺
