### ISSUE TITLE
DIN 6912

### ISSUE THREAD

**Issue by sedneck** [shaise/FreeCAD_FastenersWB#68]
Please include the screws DIN-6912.

**Comment by luzpaz** [comment]
@Berberic2 perhaps you'd be willing to addt this as well ?

**Comment by luzpaz** [comment]
@sedneck care to test ?

**Comment by luzpaz** [comment]
Thanks berberic2!  

@shaise please close ticket + Do you mind updating the wiki (https://wiki.freecadweb.org/Fasteners_Workbench#Fasteners_Screws) ?

**Comment by shaise** [comment]
I have no wiki account/permission.

**Comment by luzpaz** [comment]
@shaise no worries. I added it. Ticket can be closed

**Comment by shaise** [comment]
perhaps I should have wiki permissions, in case I want to edit/fix my wb related things

**Comment by luzpaz** [comment]
https://forum.freecadweb.org/viewtopic.php?f=21&t=6830

**Comment by luzpaz** [comment]
@shaise please close ticket. thanks

**Comment by shaise** [comment]
closed.
