### ISSUE TITLE
No Fasteners Workbench show in Workbench

### ISSUE THREAD

**Issue by wolf-skin** [shaise/FreeCAD_FastenersWB#69]
I use version 0.18 in Windows 10, after install it from Addon Manager, no Fastener show in Workbench. 

The programs are stored in "C:\Users\{User Name}\AppData\Roaming\FreeCAD\Mod\fasteners" already.

![image](https://user-images.githubusercontent.com/17585808/88609764-878d5300-d0b7-11ea-9c76-fa2753728fd3.png)

Thanks!

**Comment by shaise** [comment]
what do you mean? I see it in your picture. line 5.

**Comment by wolf-skin** [comment]
Sorry mate, my mistake, I overlook it. Thanks!
