### ISSUE TITLE
PCB Metric Standoff

### ISSUE THREAD

**Issue by leoheck** [shaise/FreeCAD_FastenersWB#72]
Hi, I am trying to use the PCB Metric Standoff, but it does not allow me to change settings freely. Only few options on the list.
For instance, I would like to create this one, but the lengths available are 10 mm and 12 mm. The length is a list and not an input field. There is no way to type 11 mm there.

![image](https://user-images.githubusercontent.com/1277920/92047425-74773e00-ed5b-11ea-8456-b526de77175e.png)

**Comment by shaise** [comment]
Hi @leoheck ,

I have just added a feature that lets you set custom lengths. Please update, try, and let me know. 
Note: If you are loading an old file with standoffs of previous version, you need to recompute them for this setting to appear.

shai

**Comment by leoheck** [comment]
Yay! This is nice. I will try it right now @shaise

**Comment by leoheck** [comment]
It is working just fine but I have another and related question.
The threaded part of this standoff, is 6mm, how do I set that?

I am thinking it is on width. But I can't change the `5` there.
![image](https://user-images.githubusercontent.com/1277920/92131006-d11a3d80-eddb-11ea-8bf5-35fc7a04e403.png)

**Comment by shaise** [comment]
Sorry, you can't. This is the standard. the width is not related. the width is for M3 standoff. There are several width standards (the hex body thickness)

**Comment by easyw** [comment]
@shaise I think @leoheck was referring to the length of the screw part of the standoff... some manufacturer have a slightly different length i.e. instead of 6mm, 4mm or 5mm

**Comment by leoheck** [comment]
Yes, that's right @easyw 
Do you think it is possible to add a custom length for that treaded part as well?

**Comment by shaise** [comment]
Done.
