### ISSUE TITLE
Self Tapping Screws

### ISSUE THREAD

**Issue by leoheck** [shaise/FreeCAD_FastenersWB#74]
Hello, 

I was trying to find these self-tapping screws that work really well with plastics.
For instance, size M2.6 that I need to use with a pointy tip. 

![image](https://user-images.githubusercontent.com/1277920/93372544-67158580-f82a-11ea-9a2c-9878061496f1.png)

My reference is here.
https://www.amazon.com/Tapping-400Pcs-Screws-Assortment-Plastic/dp/B07VQZXGH2

Can you tell me if we have this in this workbench?
Also, if it is not there yet, is it possible to ask this as a feature request?

**Comment by leoheck** [comment]
@shaise do you know anything about these self-tapping screws or at least if it is possible to use M2.6 somewhere?

**Comment by shaise** [comment]
Sorry, but no self tapping screws yet. The fasteners WB is based on the screw-maker macro, and it does not have it either.

**Comment by leoheck** [comment]
Thanks for letting me know. Where I can find this screw-maker macro. Is it possible to ask this as a feature request there? Or even better, offer any kind of help there?

**Comment by shaise** [comment]
https://github.com/ulrich1a/screw_maker. not sure how active it is.

**Comment by leoheck** [comment]
The project has a couple of years but the latest update was 3 months ago. It looks that is not forgotten. I am going to make a request there. Lets see.

**Comment by FreeCAD-Tools** [comment]
It seems to me as a basis for Self Tapping Screws may can use DIN571 screw. Just need to change the cap.
But I do not competence in the code of the formation of screws.

![изображение](https://user-images.githubusercontent.com/90561109/192611269-3292c030-40dc-4879-a199-d4e03867706c.png)

**Comment by luzpaz** [comment]
Perhaps related #138

**Comment by shaise** [comment]
DIN571 is implemented now.

**Comment by EA32** [comment]
![image](https://user-images.githubusercontent.com/116030160/201708779-1ad67617-9851-46cb-9e6b-f6efec2f49f0.png)

At this moment, GOST 1144(2) and GOST 1144(4) Wood Screws is available, they are not is Self-Tapping Screws, but have thread with very similar profile and along the entire length. Their have semi-sphere heads.

**Comment by luzpaz** [comment]
@alexneufeld any possibility you'd be interested in implementing this ?

**Comment by alexneufeld** [comment]
Sure

**Comment by hasecilu** [comment]
Hi, I sent a PR for some self taping screws if someone want to check/test.
