### ISSUE TITLE
Minor issue with screws that have custom lenght more than 50mm

### ISSUE THREAD

**Issue by leoheck** [shaise/FreeCAD_FastenersWB#79]
Super minor issue.
I am creating a screw with custom length and it is more than 50mm (74mm to be precise)
And it is showing this line in the middle.
![image](https://user-images.githubusercontent.com/1277920/100489230-d55fa980-30f1-11eb-9e2e-eeb8859211fd.png)

**Comment by shaise** [comment]
Yes, For long screws, usually the part below the line represents the "threaded" part, and the top is the "smooth" part.
