### ISSUE TITLE
Scale thread for 3D printing does not seem to work.

### ISSUE THREAD

**Issue by jf1452** [shaise/FreeCAD_FastenersWB#80]
I have played with the scaling option for threads for 3D printing, but no setting seems to change the 3D printed size.
![image](https://user-images.githubusercontent.com/2996505/103666471-faf39480-4f74-11eb-8e44-3d2a8e1de955.png)

On the whole, this is an excellent workbench; thank you for creating it.

**Comment by shaise** [comment]
you need to mark the object for recalculation then press the recalculate button for the settings to take effect

**Comment by jf1452** [comment]
Thank you @shaise ; yes that has fixed it; thank you for your answer
