### ISSUE TITLE
Request: README instructions how to add fasteners to this WB

### ISSUE THREAD

**Issue by luzpaz** [shaise/FreeCAD_FastenersWB#95]
It would be beneficial to have some guidance for those who have the ability and the want to add fasteners to this WB on how to do so. 

> I have access to the norm, if someone writes somewhere a small guide on how to add sizes to iso10642def.csv i can do a pull request for it. I had a look but the numbers are unclear to me (also because I am mostly a coder).
> 
> Btw, fasteners.eu is not updated to :2019 version

ref: @diniciacci in https://github.com/shaise/FreeCAD_FastenersWB/issues/89#issuecomment-842652885

Edit: [forum thread request](https://forum.freecadweb.org/viewtopic.php?f=8&t=11429&p=511989#p511989)

**Comment by bambukouk** [comment]
see also #88

**Comment by luzpaz** [comment]
Closed by #99 
Thanks @alexneufeld!
